# -*- coding: utf-8 -*-
"""try2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WJgNShytRyMYDBsO_6xHZzG2wmz_ObKQ
"""

!pip install flask nltk requests spacy
!python -m spacy download en_core_web_md

import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

from flask import Flask, render_template, request
import requests
import random
import math
from collections import Counter, defaultdict
import spacy
from nltk.tokenize import word_tokenize

# Data Loading & Preprocessing
def load_data():
    url = "https://www.gutenberg.org/cache/epub/2591/pg2591.txt"
    response = requests.get(url)
    text = response.text
    return text

def preprocess(text):
    start = text.find('*** START OF')
    end = text.find('*** END OF')
    if start != -1 and end != -1:
        text = text[start:end]
    text = text.replace('\n', ' ').replace('\r', ' ')
    tokens = word_tokenize(text.lower())
    clean_tokens = []
    for t in tokens:
        if t.isalpha():
            clean_tokens.append(t)
        elif t in ['.', '?', '!']:
            clean_tokens.append(t)
    return clean_tokens

def build_ngram_model(tokens, n=3):
    model = defaultdict(Counter)
    for i in range(len(tokens)-n):
        context = tuple(tokens[i:i+n-1])
        next_word = tokens[i+n-1]
        model[context][next_word] += 1
    return model

# Sentence Generation
def generate_sentence(model, start_words, min_len=10, max_len=12):
    words = start_words.lower().split()
    sentence = words[:]
    n = len(list(model.keys())[0]) + 1
    for _ in range(max_len - len(words)):
        context = tuple(sentence[-(n-1):])
        if context not in model:
            break
        next_words = model[context]
        next_word = random.choices(list(next_words.keys()), weights=next_words.values())[0]
        if next_word in ['.', '?', '!'] and len(sentence) < min_len:
            continue
        sentence.append(next_word)
        if next_word in ['.', '?', '!'] and len(sentence) >= min_len:
            break
    return ' '.join(sentence)

# Evaluation Metrics
def perplexity(model, sentence):
    words = sentence.lower().split()
    n = len(list(model.keys())[0]) + 1
    N = len(words)
    log_prob = 0
    for i in range(n-1, N):
        context = tuple(words[i-n+1:i])
        word = words[i]
        if context in model and word in model[context]:
            prob = model[context][word] / sum(model[context].values())
        else:
            prob = 1e-6
        log_prob += -math.log(prob)
    return math.exp(log_prob / N)

def fluency(model, sentence):
    return 1 / perplexity(model, sentence)

def coherence(sentence):
    words = sentence.split()
    sims = []
    for i in range(len(words)-1):
        w1, w2 = nlp(words[i]), nlp(words[i+1])
        if w1.vector_norm and w2.vector_norm:
            sims.append(w1.similarity(w2))
    return sum(sims)/len(sims) if sims else 0

# Load spaCy for coherence
nlp = spacy.load("en_core_web_md")

# Load data and build models
print("Loading data...")
text_data = load_data()
print("Preprocessing tokens...")
tokens = preprocess(text_data)

print("Building models...")
bigram_model = build_ngram_model(tokens, n=2)
trigram_model = build_ngram_model(tokens, n=3)
fourgram_model = build_ngram_model(tokens, n=4)

models = {
    "Bigram": bigram_model,
    "Trigram": trigram_model,
    "Fourgram": fourgram_model
}
print("Models built successfully!")

HTML_TEMPLATE = '''
<!DOCTYPE html>
<html>
<head>
    <title>N-Gram Language Model Text Generator</title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
        .container { background: #f5f5f5; padding: 20px; border-radius: 10px; }
        .form-group { margin-bottom: 15px; }
        label { display: block; margin-bottom: 5px; font-weight: bold; }
        input, select, button { width: 100%; padding: 8px; margin-bottom: 10px; }
        button { background: #007cba; color: white; border: none; padding: 10px; cursor: pointer; }
        button:hover { background: #005a87; }
        .result { background: white; padding: 15px; margin: 10px 0; border-radius: 5px; }
        .metrics { font-size: 0.9em; color: #666; }
    </style>
</head>
<body>
    <div class="container">
        <h1>N-Gram Language Model Text Generator</h1>
        <form method="POST">
            <div class="form-group">
                <label for="model_choice">Choose N-Gram Model:</label>
                <select name="model_choice" id="model_choice">
                    <option value="Bigram">Bigram</option>
                    <option value="Trigram">Trigram</option>
                    <option value="Fourgram">Fourgram</option>
                </select>
            </div>

            <div class="form-group">
                <label for="start_words">Enter starting words:</label>
                <input type="text" name="start_words" id="start_words" value="once upon" required>
            </div>

            <div class="form-group">
                <label for="num_sentences">Number of sentences to generate: <span id="num_sentences_value">3</span></label>
                <input type="range" name="num_sentences" id="num_sentences" min="1" max="5" value="3">
            </div>

            <div class="form-group">
                <label for="min_len">Minimum length of sentence: <span id="min_len_value">10</span></label>
                <input type="range" name="min_len" id="min_len" min="5" max="20" value="10">
            </div>

            <div class="form-group">
                <label for="max_len">Maximum length of sentence: <span id="max_len_value">15</span></label>
                <input type="range" name="max_len" id="max_len" min="10" max="30" value="15">
            </div>

            <button type="submit">Generate</button>
        </form>

        {% if results %}
        <h2>Generated Sentences & Evaluation</h2>
        {% for result in results %}
        <div class="result">
            <strong>Sentence:</strong> {{ result.sentence }}<br>
            <div class="metrics">
                Perplexity: {{ result.perplexity }} |
                Fluency: {{ result.fluency }} |
                Coherence: {{ result.coherence }}
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>

    <script>
        document.getElementById('num_sentences').addEventListener('input', function() {
            document.getElementById('num_sentences_value').textContent = this.value;
        });
        document.getElementById('min_len').addEventListener('input', function() {
            document.getElementById('min_len_value').textContent = this.value;
        });
        document.getElementById('max_len').addEventListener('input', function() {
            document.getElementById('max_len_value').textContent = this.value;
        });
    </script>
</body>
</html>
'''

# Initialize Flask app
app = Flask(__name__)

@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        # Get form data
        model_choice = request.form['model_choice']
        start_words = request.form['start_words']
        num_sentences = int(request.form['num_sentences'])
        min_len = int(request.form['min_len'])
        max_len = int(request.form['max_len'])

        # Generate sentences
        model = models[model_choice]
        results = []

        for _ in range(num_sentences):
            sentence = generate_sentence(model, start_words, min_len, max_len)
            results.append({
                'sentence': sentence,
                'perplexity': f"{perplexity(model, sentence):.2f}",
                'fluency': f"{fluency(model, sentence):.4f}",
                'coherence': f"{coherence(sentence):.4f}"
            })

        return render_template_string(HTML_TEMPLATE, results=results)

    return render_template_string(HTML_TEMPLATE, results=None)

def render_template_string(template, **context):
    from jinja2 import Template
    return Template(template).render(**context)

# Run the Flask app
if __name__ == '__main__':
    from google.colab.output import eval_js
    print("Starting Flask server...")
    print("Click on the URL below to access your application:")
    print(eval_js("google.colab.kernel.proxyPort(5000)"))
    app.run(host='0.0.0.0', port=5000, debug=False)

